[config]
schemaVersion = "0.0.1"


[package]
namespace = "RoboBro"
name = "Meligrowe"
versionNumber = "1.0.1"
description = "Size-changing toybox for Hades 2! Grow Melinoe bigger or shrink her smaller as you play a run. Make her voice pitch deeper or higher. Highly configurable!"
websiteUrl = "https://github.com/BlueKingBar/Meligrowe"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.55"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", "misc", ]
